version: 0.1
log:
  level: warn
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: 10.8.0.1:5000
  tls:
    certificate: /etc/distribution/registry.crt
    key: /etc/distribution/registry.key
auth:
  htpasswd:
    realm: launchstead
    path: /etc/distribution/htpasswd
