//go:build linux

package nodelaunch

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"io/fs"
	"os"
	"runtime"
	"strings"
	"syscall"
	"time"

	"github.com/0xivanov/self-hosted-deployer-admin-panel/internal/nodeartifact"
	"golang.org/x/sys/unix"
)

// InstallRelease validates and extracts an archive into a private staging
// directory, seals it root-owned/read-only, then publishes a fresh release name
// with an atomic no-replace rename. It never executes uploaded code. The supplied
// root and its ancestors must be controlled by the trusted agent and accessible
// only inside the project's dedicated runtime boundary.
//
// On error after publication, the returned Directory remains nonempty: keep that
// release for reconciliation, and do not start it. A successful return means the
// files and parent directory have been synced, not that power-loss recovery or
// runtime suitability has been qualified. The caller owns orphan cleanup.
func InstallRelease(ctx context.Context, data []byte, expected string, releases *os.Root) (result nodeartifact.Release, err error) {
	return installReleaseAt(ctx, data, expected, "", releases)
}

func installReleaseAt(ctx context.Context, data []byte, expected, destination string, releases *os.Root) (result nodeartifact.Release, err error) {
	if destination != "" && (!strings.HasPrefix(destination, "release-") || !id(strings.TrimPrefix(destination, "release-"))) {
		return result, ErrAssignment
	}
	if os.Geteuid() != 0 || releases == nil {
		return result, ErrAssignment
	}
	info, err := releases.Stat(".")
	if err != nil || !info.IsDir() || !rootOwned(info) || info.Mode().Perm()&0022 != 0 {
		return result, ErrAssignment
	}
	if err = ctx.Err(); err != nil {
		return result, err
	}
	var entropy [32]byte
	if _, err = rand.Read(entropy[:]); err != nil {
		return result, err
	}
	stagingName := ".install-" + hex.EncodeToString(entropy[:])
	if err = releases.Mkdir(stagingName, 0700); err != nil {
		return result, err
	}
	defer func() { err = errors.Join(err, releases.RemoveAll(stagingName)) }()
	staging, err := releases.OpenRoot(stagingName)
	if err != nil {
		return result, err
	}
	defer staging.Close()
	extracted, err := nodeartifact.Extract(ctx, data, expected, staging)
	if err != nil {
		return result, err
	}
	release, err := staging.OpenRoot(extracted.Directory)
	if err != nil {
		return result, err
	}
	err = sealRelease(ctx, release)
	closeErr := release.Close()
	if err = errors.Join(err, closeErr); err != nil {
		return result, err
	}
	if err = ctx.Err(); err != nil {
		return result, err
	}
	// Both paths are generated by trusted code below the same pinned root. The
	// no-replace flag also protects an existing directory in the unlikely event of
	// a random-name collision, without a check-then-rename race.
	parent, err := releases.Open(".")
	if err != nil {
		return result, err
	}
	defer parent.Close()
	if destination == "" {
		destination = extracted.Directory
	}
	if err = unix.Renameat2(int(parent.Fd()), stagingName+"/"+extracted.Directory, int(parent.Fd()), destination, unix.RENAME_NOREPLACE); err != nil {
		return result, err
	}
	result = extracted
	result.Directory = destination
	// Persist removal from the staging directory as well as insertion into parent.
	source, err := staging.Open(".")
	if err != nil {
		return result, err
	}
	err = errors.Join(source.Sync(), source.Close(), parent.Sync())
	return result, err
}
func rootOwned(info fs.FileInfo) bool {
	stat, ok := info.Sys().(*syscall.Stat_t)
	return ok && stat.Uid == 0 && stat.Gid == 0
}
func sealRelease(ctx context.Context, root *os.Root) error {
	var directories []string
	err := fs.WalkDir(root.FS(), ".", func(name string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if err := ctx.Err(); err != nil {
			return err
		}
		info, err := root.Lstat(name)
		if err != nil {
			return err
		}
		if !rootOwned(info) {
			return ErrAssignment
		}
		if info.IsDir() {
			directories = append(directories, name)
			return nil
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return nil
		} // Already validated internal file links; never chmod through them.
		if !info.Mode().IsRegular() {
			return ErrAssignment
		}
		file, err := root.Open(name)
		if err != nil {
			return err
		}
		mode := os.FileMode(0444)
		if info.Mode().Perm()&0111 != 0 {
			mode = 0555
		}
		err = errors.Join(file.Chmod(mode), file.Sync(), file.Close())
		return err
	})
	if err != nil {
		return err
	}
	for i := len(directories) - 1; i >= 0; i-- {
		if err = ctx.Err(); err != nil {
			return err
		}
		directory, e := root.Open(directories[i])
		if e != nil {
			return e
		}
		if err = errors.Join(directory.Chmod(0555), directory.Sync(), directory.Close()); err != nil {
			return err
		}
	}
	return nil
}

// LinuxInstaller installs into the operation's reserved destination. It must be
// used inside the runtime identified by the pool configuration. The caller keeps
// the root and installed content protected for the reservation's entire lifetime.
type LinuxInstaller struct{ Releases *os.Root }

func (i LinuxInstaller) InstallNodeRelease(ctx context.Context, a Assignment, data []byte) (nodeartifact.Release, error) {
	if _, err := Render(a); err != nil {
		return nodeartifact.Release{}, err
	}
	if a.Architecture != runtime.GOARCH {
		return nodeartifact.Release{}, ErrAssignment
	}
	return installReleaseAt(ctx, data, a.ArtifactSHA256, a.ReleaseDirectory, i.Releases)
}

// ObserveNodeInstallation verifies and syncs a sealed release without changing
// its contents or running code. It does not re-seal damaged files to hide drift.
func (i LinuxInstaller) ObserveNodeInstallation(ctx context.Context, a Assignment, data []byte) (InstallationObservation, error) {
	var out InstallationObservation
	if _, err := Render(a); err != nil {
		return out, err
	}
	if os.Geteuid() != 0 || a.Architecture != runtime.GOARCH || i.Releases == nil {
		return out, ErrAssignment
	}
	parent, err := i.Releases.Stat(".")
	if err != nil || !parent.IsDir() || !rootOwned(parent) || parent.Mode().Perm()&0022 != 0 {
		return out, ErrAssignment
	}
	info, err := i.Releases.Lstat(a.ReleaseDirectory)
	if err != nil {
		return out, err
	}
	if !info.IsDir() || !rootOwned(info) {
		return out, ErrAssignment
	}
	root, err := i.Releases.OpenRoot(a.ReleaseDirectory)
	if err != nil {
		return out, err
	}
	defer root.Close()
	manifest, err := nodeartifact.VerifySealed(ctx, data, a.ArtifactSHA256, root)
	if err != nil {
		return out, err
	}
	var directories []string
	err = fs.WalkDir(root.FS(), ".", func(name string, _ fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if err := ctx.Err(); err != nil {
			return err
		}
		info, err := root.Lstat(name)
		if err != nil {
			return err
		}
		if !rootOwned(info) {
			return ErrAssignment
		}
		if info.IsDir() {
			directories = append(directories, name)
			return nil
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return nil
		}
		if !info.Mode().IsRegular() || info.Sys().(*syscall.Stat_t).Nlink != 1 {
			return ErrAssignment
		}
		file, err := root.Open(name)
		if err != nil {
			return err
		}
		return errors.Join(file.Sync(), file.Close())
	})
	if err != nil {
		return out, err
	}
	for n := len(directories) - 1; n >= 0; n-- {
		if err = ctx.Err(); err != nil {
			return out, err
		}
		dir, e := root.Open(directories[n])
		if e != nil {
			return out, e
		}
		if err = errors.Join(dir.Sync(), dir.Close()); err != nil {
			return out, err
		}
	}
	dir, err := i.Releases.Open(".")
	if err != nil {
		return out, err
	}
	if err = errors.Join(dir.Sync(), dir.Close(), ctx.Err()); err != nil {
		return out, err
	}
	return InstallationObservation{Assignment: a, Manifest: manifest, ObservedAt: time.Now()}, nil
}
